### ISSUE TITLE
Fails to be loaded with plug.kak

### ISSUE THREAD

**Issue by andreyorst** [occivink/kakoune-gdb#8]
Thanks for great blugin!

But it fails to load with my [plugin manager](https://github.com/andreyorst/plug.kak). I've used your plugin with this configuration:
```kaksh
plug "occivink/kakoune-gdb"
```
But after last update it started to throw errors:
```
/home/andreyorst/.config/kak/plugins/kakoune-gdb/detail/gdb.kak:48:2115: 'addhl' duplicate id: 'gdb'
```

The problem is that plug.kak tries to load all `*.kak` files in the repo. But I've noticed that now you have two kak scripts:
```
./gdb.kak
./detail/gdb.kak
```

How should I load this plugin now? Do I need second file?

plug.kak can load parts of plugins by using names of files to load, but in case of your plugin I can't do that since both files have same names:
```sh
plug "occivink/kakoune-gdb" load %{
    gdb.kak
}
# will still load both files, since gdb.kak is argument for file command.
```

**Comment by occivink** [comment]
Ah yeah, I recently introduced a "build" step where I combine the kak script (the one in detail/) with the perl one to produce the top level gdb.kak, it makes it much easier to develop. 
But I also keep the result of the build within the repo so that one can simply copy-paste gdb.kak in their own config without building anything (not the best practice, but I think it's convenient). 

I think I'll simply rename the one in `detail/` to gdb.kak.tmp or something, it's kind of a build detail.

**Comment by andreyorst** [comment]
Understood! `gdb.kak.tmp` would work fine, since default argument for find is `*.kak`
So you'll close the issue after that?

**Comment by occivink** [comment]
Yeah. I'm just trying to think if there's not a better way, considering that I like having the highlighting recognized even for the 'tmp' file on which I work.

**Comment by andreyorst** [comment]
Thanks!
